version: '2'
services:
    courseos-app:
        image: courseos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://courseos-mysql:3306/courseos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    courseos-mysql:
        extends:
            file: mysql.yml
            service: courseos-mysql
